### ISSUE TITLE
Add m4a, ogg, ... etc format to upload

### ISSUE THREAD

**Issue by minh6a** [thebigmunch/google-music-proto#5]
**Please read the contributing guidelines linked above and delete this message before opening an issue.**

https://support.google.com/googleplaymusic/answer/1100462?hl=en

I think this should be doable and easy to implement (either using the existing FLAC format code here or force ffmpeg and transcode it to mp3 320k in gms)

**Comment by thebigmunch** [comment]
> I think this should be doable and easy to implement (either using the existing FLAC format code here or force ffmpeg and transcode it to mp3 320k in gms)

Please don't come in here telling me what would be easy to implement when you clearly don't understand the process (or at all).

Let's just assume we made all the (substantial) changes that would be required to allow files not supported by my ``audio-metadata`` library to make it to the code here (would require using mutagen for files ``audio-metadata`` doesn't yet support)... this code can't generate a correct client ID without my ``audio-metadata`` library. Also, I'm not adding a dependency on another audio metadata library. Part of the reason for my library's existence is that ``mutagen`` doesn't provide the information necessary to generate a correct client ID for most files and ``gmusicapi`` doesn't even do so for the files it does (mostly just FLAC). So, let's also say we just spoof the client ID... we'd also need to add that mutagen dependency here to fill in the track metadata during the upload process else you'd end up with no metadata on Google Music. Did I already say I wasn't going to do that? Pretty sure I did.

So, if you want to hurry support for other formats, feel free to volunteer to write that support into ``audio-metadata`` or send some people who are willing my way. Otherwise, you'll have to wait until I get to it.
